---
title: "Situacion-Camas"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(plotly)
library(gsheet)
library(shiny)
library(DT)
library(gsheet)


```




```{r}

require(RCurl)
u <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vQVdJTpat7rKkgBdB7GfM220Y95vHJoJDH5XQHxI6zaRaeS8YGKMa5Rxnrium04E9-r5c1mF5YRr_nO/pubhtml"

library(gsheet)


cleanGoogleTable <- function(dat, table=1, skip=0, ncols=NA, nrows=-1, header=TRUE, dropFirstCol=NA){
  if(!is.data.frame(dat)){
    dat <- dat[[table]]
  }
  
  if(is.na(dropFirstCol)) {
    firstCol <- na.omit(dat[[1]])
    if(all(firstCol == ".") || all(firstCol== as.character(seq_along(firstCol)))) {
      dat <- dat[, -1]
    }
  } else if(dropFirstCol) {
    dat <- dat[, -1]
  }
  
  if(skip > 0){
    dat <- dat[-seq_len(skip), ]
  }
  
  if(nrow(dat) == 1) return(dat)
  
  
  if(nrow(dat) >= 2){
    if(all(is.na(dat[2, ]))) dat <- dat[-2, ]
  }
  if(header && nrow(dat) > 1){
    header <- as.character(dat[1, ])
    names(dat) <- header
    dat <- dat[-1, ]
  }
  
  # Keep only desired columns
  if(!is.na(ncols)){
    ncols <- min(ncols, ncol(dat))
    dat <- dat[, seq_len(ncols)]
  }
  
  
  # Keep only desired rows
  if(nrows > 0){
    nrows <- min(nrows, nrow(dat))
    dat <- dat[seq_len(nrows), ]
  }
  
  # Rename rows
  rownames(dat) <- seq_len(nrow(dat))
  dat
}
library(RCurl)
library(mosaic)

readGoogleSheet <- function(url, na.string="", header=TRUE){
  stopifnot(require(XML))
  # Suppress warnings because Google docs seems to have incomplete final line
  suppressWarnings({
    doc <- paste(readLines(url), collapse=" ")
  })
  if(nchar(doc) == 0) stop("No content found")
  htmlTable <- gsub("^.*?(<table.*</table).*$", "\\1>", doc)
  ret <- readHTMLTable(htmlTable, header=header, stringsAsFactors=FALSE, as.data.frame=TRUE)
  lapply(ret, function(x){ x[ x == na.string] <- NA; x})
}


g <- readGoogleSheet("https://docs.google.com/spreadsheets/d/e/2PACX-1vQVdJTpat7rKkgBdB7GfM220Y95vHJoJDH5XQHxI6zaRaeS8YGKMa5Rxnrium04E9-r5c1mF5YRr_nO/pubhtml")


#data <- cleanGoogleTable(g, table=1)

data1 <- cleanGoogleTable(g, table=1)
data2 <- cleanGoogleTable(g, table=2)
data3 <- cleanGoogleTable(g, table=3)


```
Inputs {.sidebar data-width=1}
-----------------------------------------------------------------------

```{r}

jscode <- "shinyjs.refresh = function() { history.go(0); }"


actionButton(jscode, "Refresh")

observeEvent(input$reset, {

})

```


# SECTOR H

## CABEZAL
### KPI1
```{r}
estatus <- data1 %>% filter(COD ==1)
valueBox(estatus$ESTATUS)

```

### KPI 2
```{r}
estatus <- data1 %>% filter(COD ==2)
valueBox(estatus$ESTATUS)
```

### KPI 3
```{r}
estatus <- data1 %>% filter(COD ==3)
valueBox(estatus$ESTATUS)
```


## COLUMNA 1
### CAJA 1


### CAJA 2


### CAJA 3

### CAJA 4

## COLUMNA 2

### CAJA 5
### CAJA 6
### CAJA 7
### CAJA 8

## COLUMNA 3
### CAJA 9
### CAJA 10
### CAJA 11
### CAJA 12

# SECTOR M
## CABEZAL
### KPI1
### KPI 2
### KPI 3

## COLUMNA 1
### CAJA 1
### CAJA 2
### CAJA 3
### CAJA 4

## COLUMNA 2
### CAJA 5
### CAJA 6
### CAJA 7
### CAJA 8

## COLUMNA 3
### CAJA 9
### CAJA 10
### CAJA 11
### CAJA 12

# SETCOR E
## CABEZAL
### KPI1
### KPI 2
### KPI 3

## COLUMNA 1
### CAJA 1
### CAJA 2
### CAJA 3
### CAJA 4

## COLUMNA 2
### CAJA 5
### CAJA 6
### CAJA 7
### CAJA 8

## COLUMNA 3
### CAJA 9
### CAJA 10
### CAJA 11
### CAJA 12